export const FETCH_ALL_ADVERTISEMENTS = "FETCH_ALL_ADVERTISEMENTS";

export const FETCH_USER_ADVERTISEMENTS = "FETCH_USER_ADVERTISEMENTS";

export const LOADING_ADVERTISEMENTS = "LOADING_ADVERTISEMENTS";
