export const FETCH_PUBLIC_ADVERTISEMENTS = "FETCH_PUBLIC_ADVERTISEMENTS";

export const FETCH_USER_ADVERTISEMENTS = "FETCH_USER_ADVERTISEMENTS";

export const SET_LAST_CREATED_ADVERTISEMENT = "SET_LAST_CREATED_ADVERTISEMENT";
