export const FETCH_PUBLIC_ADVERTISEMENTS = "FETCH_PUBLIC_ADVERTISEMENTS";

export const FETCH_USER_ADVERTISEMENTS = "FETCH_USER_ADVERTISEMENTS";

export const LOADING_ADVERTISEMENTS = "LOADING_ADVERTISEMENTS";
